#!/usr/bin/with-contenv bash

shopt -s nocasematch
if [[ $DEBUG == "true" ]]
 then
        set -x
fi

: ${DISABLE_CRON:="true"}

if [[ $DISABLE_CRON == "false" ]]
 then
	exec /usr/sbin/fcron -f
 else
	s6-svc -d /run/s6/services/fcron
fi
